### ISSUE TITLE
trim inclination and the engine's fuel consumption

### ISSUE THREAD

**Issue by CelsoKupsch** [buhhe/VolvoPenta-N2K_Interface#1]
Hi Buhhe, I found it very interesting what you managed to do I'm assembling my hardware and a doubt arose in your software, how would I go about including the trim inclination and the engine's fuel consumption? Do you know how to include this information?

**Comment by buhhe** [comment]
Hi Celso,
there are two points to be cleared:
1) The data you wish must be available on the VP-bus. My D1-20 MDI sends neither fuel consumption nor trim inclination data  as far I know. And I did not find any note that these data are available. But maybe your bus sends these data.
2) The data used in the VP-Canbus are not disclosed by VP, similar to some NMEA2000 data. So it's a question of knowing in which PGN the data can be found if they are really available on the bus. I did many research in the internet an what i found in public sources are only the data which are implemented now. That is RPM, coolant temperature, engine hours and alternator voltage. If you know about public sources describing more VP-PGN's pls. let me know.

If both conditions are met you can extend the "switch" statement from line 137 to:
- catch the J1939 datagrams and to extract the appropriate values
- put the values i a N2K datagram and send it to the bus.

Look at the code at line 139-144. It's very similar to what you have to do.

**Comment by CelsoKupsch** [comment]
https://www.marinpro.com/Cms_Data/Contents/powerhouse/Folders/Accessories/AccessoryFiles/~contents/4YD2DR3WYE3MEBNA/OpenCAN_InstallGuideline_rev_1.pdf
Hello, I found this document that has the Volvo Penta PGN's for other information. See if I'm understanding correctly:
case 65266: Engine fuel rate + Data [?] *constant

**Comment by buhhe** [comment]
In principle, yes. And you need to find out which bits of the 8-byte payload in this PGN contain the fuel consumption data and how this is represented.
