### ISSUE TITLE
Compilation Error...

### ISSUE THREAD

**Issue by woodstock37s** [buhhe/VolvoPenta-N2K_Interface#2]
Hi,
I am trying to buildt the VP Interface, but keep getting an error message while compiling.
_....\VolvoPenta-N2K_Interface-main\libraries\Aruino_CAN_BUS_MCP2515-master/mcp_can.h:105:10: note:   candidate expects 2 arguments, 3 provided

exit status 1

Compilation error: 'MCP_ANY' was not declared in this scope_

I am a rookie...so maybe I have done something wrong?
I am using Arduino IDE and did install the NMEA and CAN libraries out of the zip files.

Thank you

**Comment by buhhe** [comment]
Hi woodstock37s,
there are two issues in the pathname of your mcp_can.h which are somewhat strange.

_....\VolvoPenta-N2K_Interface-main\libraries\Aruino_CAN_BUS_MCP2515-master/mcp_can.h
                                                                     ^1^                                             ^2^

1: It should be Arduino, not Aruino (missing 'd')
2: Supposing you are using a windows environment that should be a backslash not a slash like the other backslaches.

Pls. check if you can open mcp_can.h using that pathname.
If yes pls. send me a copy of your mcp_can.h.Maby it differs from mine.

**Comment by woodstock37s** [comment]
Thank you for answering!
I have used the mcp_can.h from the two sources mentioned in the pdf. tried both.
I attached the fulll error log file and the two library.zips I have tried

[Aruino_CAN_BUS_MCP2515-master.zip](https://github.com/buhhe/VolvoPenta-N2K_Interface/files/10356197/Aruino_CAN_BUS_MCP2515-master.zip) from https://github.com/coryjfowler
[CAN_BUS_Shield-master.zip](https://github.com/buhhe/VolvoPenta-N2K_Interface/files/10356202/CAN_BUS_Shield-master.zip) from https://github.com/ttlappalainen/CAN_BUS_Shield

.
[CompileErrorLog.txt](https://github.com/buhhe/VolvoPenta-N2K_Interface/files/10356194/CompileErrorLog.txt)

**Comment by woodstock37s** [comment]
when I use the [coryjfowler](https://github.com/coryjfowler)
/
[MCP_CAN_lib](https://github.com/coryjfowler/MCP_CAN_lib) it works....
