### ISSUE TITLE
Do clear description for 12V or 5V Power

### ISSUE THREAD

**Issue by BerndCirotzki** [buhhe/VolvoPenta-N2K_Interface#3]
Hello Buhle,
I found Interface, and would like to build it. but there are not clear differences in your descriptin.
in document 20211215 J1939.

you wrote toe power must set down from 12V to 5V  Power from CAN. But witch CAN ! There are too.
I Don't need a power vom N2k CAN, when I can take the power from VolvoCAN J1939.
and there you discribed once :
page 1:
"Since the ESP32 needs 5V power supply and the CAN-Bus power is 12V you need a step-down
converter to 5V."   Ok, CAN N2k or CAN Volvo ?
and then on page 3 : 
Pin assignement:
....
• 6 + power 5V

what is right ? Has the Volvo J1939  12V or 5V ?

Bernd

**Comment by buhhe** [comment]
Bernd,
As outlined in the document, the N2K bus and the motor bus are both CAN-based bus systems, differing only in the datagrams used: One is NMEA2000, the other SAE J1939. Both buses operate at 12V and are physically identical.  
Further information can be found through a Google search.
The circuit diagram shows that the electronics are powered through the VP Canbus, which only operates when the engine is switched on.To prevent the ESP32 from burning out, it should be operated with a maximum of 5V, requiring a step-down converter.
If a German manual is easier to understand, have a look here: https://open-boat-projects.org/de/volvo-penta-nmea2000-interface/
